### PR TITLE
Adjustement in Template.json

### PR DESCRIPTION
**Pull request by pilax**
- Small error found in the template.json : 
Some \n were \\n, so did't display carriage return correctly

- Updating translation (see commit details)

### CODE REVIEW

**Comment by brainfoolong** [comment]
This cannot be changed as it is the original from the CSV files, when this is changed, it cannot be inserted back again into CSV file because the script will not find the string because that doesn't match anymore.

It has to be translated as is, with the characters in the translation. I know, it's weird, but that how this all works.

For most of the other files (all LUA) this work as intended, with real newline characters. For the CSV ones, we must keep it as is.

**Comment by brainfoolong** [comment]
PS: The `template.json` is also generated fully automated, so in general no manual manipulation is possible. This is pretty usefull when a new version comes out, i just have to run the script again and all keys are automatically found and in inserted into `template.json`.

**Comment by pilax** [comment]
Osorry, not knowing how your tools work in the background, I thought I'd do well, still sorry!

So I cancel my request for commit, and will have to resume the template.json of your git :)

**Comment by brainfoolong** [comment]
No problem, you can't have known this. Yes, just please create a new pull request with just your translation files changed.

**Comment by pilax** [comment]
How I can cancel this pull request ? 
Don't found, I'm not a github regular :/

**Comment by brainfoolong** [comment]
Best way, i guess, is to manually copy the original template.json over the new one, commit and than add this to this pull request.

**Comment by pilax** [comment]
Ok, I'll try.
But other way maybe, Can you refuse this pull request ?
I already copy template.json in local ;)

Sorry for this things :(

**Comment by brainfoolong** [comment]
Is closed.

**Comment by pilax** [comment]
Ok I know how to go back on my side without losing my job, although I always have a local backup.

If you can, cancel / refuse this pull request, I will make a new cleaner just after.

Thanking you

EDIT : Roolback OK.
Sorry for this wasted time: /

**Comment by brainfoolong** [comment]
Github is not so easy sometimes, i have problems with that too, often :)

**Comment by pilax** [comment]
It's sure, everything is not necessarily clear in its use !

But for once, the error comes from me completely, in the non-knowledge how your tools in background ;)

But It's ok, everything is in order right now ;)

**Pull request closed without merging**
