### PR TITLE
FR Translation End

### PR DESCRIPTION
**Pull request by pilax**
Translation Complet.
To do List:
Test in game
Adjust text or translation based on feedback

### CODE REVIEW

**Comment by brainfoolong** [comment]
Merged. Created a .zip package for that and updated the readme. Thx.
Unfortunetely, that wasn't all the translation keys. I've updated the `fr.po` with all current existing keys, quite a lot new...

**Comment by pilax** [comment]
Hello,

Thank you for validat the pull request.

Indeed, I just saw that there was a packet of lines added!
I will attack the rest of the translation.

Last night I did a test, before you accepted the request.
I generated the package fr.zip correctly, but some things were written in German.
Maybe this is fixed following your update of today's script, I have not tested yet.

I also have some problem with the Font, some characters appear with a "?". I would try to search once the finished translation where the problem comes from.

**Comment by brainfoolong** [comment]
Yes, this thing with german in FR was fixed with latest update.
I saw the font problem in the CN issue. I will try something to support all required characters. Also in german there are 1-2 fonts that miss some special chars.

**Comment by pilax** [comment]
`Yes, this thing with german in FR was fixed with latest update.`
Yes, good new, Ty !

For Font problem, you can use [this package](https://mega.nz/#!IR42jRjZ!S822zZCtIuBKklPtz6xFU_KbxF7zb-UyhoWrEzmIpTU) made available by Blue_Tree.

It's an extraction of the FR mod for FTL, with modifications made by Blue_Tree.

When FR translation will finish, I will also look for myself if I find something :)

**Comment by brainfoolong** [comment]
Great 👍

**Comment by pilax** [comment]
By the way, can you modify stat of Fr Translate on Home page please.

since there are new lines to translate, I also take the opportunity to correct small errors here and there, and standardize some therm in my translation.

State of translation: 71%

Thanking you in advance.

**Comment by brainfoolong** [comment]
Please create a pull request for that change.

**Comment by pilax** [comment]
ok no problem, I'm doing this

**Pull request merged**
