### PR TITLE
French Translate Complet

### PR DESCRIPTION
**Pull request by pilax**
End of French translation.
- Full Translate : 100%
- Font FR : OK
- Picture FR : OK

Thanks to Mengpo for his help!

The translation is now being tested in-game to correct the following errors:
- Spelling errors / Synthaxes / grammar
- Coherence of translation
- Text too big that exceeds boxes
- Untranslated Text (Hardcoded)

Any feedback will be beneficial and welcome for the quality of translation completion.

Good game everyone !

### CODE REVIEW

**Comment by brainfoolong** [comment]
Holy sh.... What a job. I must do some fixes after this merge because it touches some files that shouldn't be touched. I will do that soon.

**Comment by pilax** [comment]
I must say that Mengpo worked hard last month to complete the translation and to be able to test it in game.
Thanks again to him for his help and contribution!

No worries about the changes, take your time.
If I have things to do / edit on my side do not hesitate to let me know.

I do not know if I have asked you the question, but have you planned a simple procedure for those who want to install the translation?
Without having to go through the tools currently in place, which are especially for the translators (the resources.dat being ignored during the merge) :)

Thanks in advance :)

**Comment by brainfoolong** [comment]
The installation itself is pretty simple. Unpack the .zip to the folder. But it has one disadvantage, the resource.dat modification is not included in the .zip file. I have plans to create an "installer" that manage that. Or if not, i will simply pack the resource.dat also in the .zip folder.

**Comment by pilax** [comment]
Yeah it's very simple for some of the files, but actually the ressources.dat is not included in it as you said.
I think the simplest and at first, include it in the .zip is the simplest and fastest way to set up.

You can make a setup install once all the trad are finished, which will leave you much more time to put this in place, which is more a little more tedious it seems to me to integrate directly into the zip.

**Pull request merged**
